### ISSUE TITLE
Repair explanations for the custom enchantment items

### ISSUE THREAD

**Issue by piecrustyumyum** [Taiterio/ce#16]
There seems to be no explanations on how to repair most of the items at all in the config or on your bukkit page or anything. I was wondering if you could explain some more of the plugin and how to use it. ex. How to repair the items, How to use the items, and what ever else. It would be really helpful as I cant find anything on it.

Also if how to repair the items is by using an anvil like normal it breaks it by taking out the "&" Symbol of the name of the custom item or enchantment.

**Comment by Taiterio** [comment]
Currently there is no way to repair items beyond the ones that have this tied to their effects (Rocketboots, Flamethrower). Furthermore, the Bukkit page holds some information on the [items](http://dev.bukkit.org/bukkit-plugins/custom-enchantments/pages/custom-items/) and [enchantments](http://dev.bukkit.org/bukkit-plugins/custom-enchantments/pages/all-enchantments/).

**Comment by DrkMatr1984** [comment]
I know this issue is closed but I have 2 possible solutions : 

Use MCMMO for the Iron Block Anvil repair system and use this Plugin :
https://www.reddit.com/r/admincraft/comments/2jboz7/im_looking_for_a_simple_plugin_that_restricts/
That restricts use of an anvil to repair an item based on words in the lore. So just list all the Enchants in the config.yml for it so people can't accidently mess up their custom enchanted items.

Or possibly this:
https://www.spigotmc.org/resources/anvilpatch.5851/
I haven't tested it though to see if it also transfers the colors from Lore, but it DOES work with the names.
